name: CI_auto_create_pr
on:
  push:
    branches:
        - master
    paths:
        - '**.md'
        - '**.mdx'

jobs:
  auto-merge-astro-branch:
    permissions: write-all
    name: Auto generate pr for astro branch when master is updated
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Enable Pull Request Automerge
        run: gh pr create --base astro --head master --title "Auto Merge Astro Branch" --body "Auto Merge Astro Branch" --label "automerge"
        env:
            GH_TOKEN: ${{ github.token }}
