name: CI
on:
  pull_request_target:
    types:
        - opened
    branches:
        - astro

jobs:
  auto-merge-astro-branch:
    permissions: write-all
    name: Auto Merge Astro Branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: astro

      - name: Enable Pull Request Automerge
        run: gh pr merge "$PRNUM" --auto --squash --title "Auto Merge Astro Branch" --body "$PRBODY"
        env:
            GH_TOKEN: ${{ github.token }}
            PRNUM: ${{ github.event.pull_request.number }}
            PRBODY: ${{ github.event.pull_request.body }}
