name: CI_auto_merge
on:
  push:
    branches:
      - master
    paths:
      - '**.md'
      - '**.mdx'

jobs:
  auto-merge-blog-branch:
    name: Auto merge blog branch
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: blog

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Merge master back to blog
        run: |
            git fetch --unshallow
            git pull
            git merge --no-ff origin/master -m "Auto-merge master back to blog"
            git push

      - name: Generate a pr after after previous step failed
        if: ${{ failure() }}
        run: |
            gh pr create --base astro --head master --title "Auto Merge Astro Branch" --body "Auto Merge Astro Branch" --label "automerge"
        env:
            GH_TOKEN: ${{ github.token }}

      - name: Manual trigger astro blog build workflow
        # https://stackoverflow.com/questions/71499150/how-to-run-a-workflow-using-github-cli
        run: gh workflow run astro.yml --ref master --repo git@github.com:fw6/blog.git
        env:
            GH_TOKEN: ${{ github.token }}
        # run: |
        #     REPO_OWNER=fw6
        #     REPO_NAME=blog
        #     BRANCH=master
        #     WORKFLOW_ID=astro.yml
        #     ACCESS_TOKEN=${{ github.token }}
        #     URL="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_ID/dispatches"
        #     PAYLOAD='{"ref":"$BRANCH"}'

        #     curl -X POST -H "Accept: application/vnd.github.v3+json" \
        #         -H "Authorization: Bearer $ACCESS_TOKEN" \
        #         -H "Content-Type: application/json" \
        #         -d "$PAYLOAD" \
        #         "$URL"
